version: '3.1'

services:
  decathlon-be:
    build: decathlon-point-be
    ports:
      - "8080:8080"
  decathlon-fe:
    build: decathlonpoints-fe
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://decathlon-be:8080/actuator/health" ]
      interval: 20s
      timeout: 5s
      retries: 20
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://decathlon-be:8080/api/v1/decathlon-point
    depends_on:
      - decathlon-be
